import Diplomatico from "../assets/Diplomatico.png";
import Mount_gay_xo from "../assets/Mount_gay_xo.png";
import Zacapa_23 from "../assets/Zacapa_23.png";
import Plantation_xo from "../assets/Plantation_xo.png";
import El_dorado_15 from "../assets/El_dorado_15.png";
import Bacardi_carta_blanca from "../assets/Bacardi_carta_blanca.png";
import Bacardi_spiced from "../assets/Bacardi_spiced.png";
import Bacardi_carta_negra from "../assets/Bacardi_negra.png";
import Captain_morgan from "../assets/Captain_morgen.png";

import Absolut from "../assets/Absolut.png";
import Grey_goose from "../assets/Grey_goose.png";
import Ciroc from "../assets/Ciroc.png";
import Beluga from "../assets/Beluga.png";

import Gordons from "../assets/Gordons.png";
import Monkey_47 from "../assets/Monkey_47.png";
import Hendricks from "../assets/Hendricks.png";
import Malfy_rosa from "../assets/Malfy_rosa.png";
import Botanist from "../assets/Botanist.png";
import Sipssmith from "../assets/Sipssmith.png";
import Gin_mare from "../assets/Gin_mare.png";
import Bombay_sapphire from "../assets/Bombay_sapphire.png";

import Johnnie_walker from "../assets/Johnnie_walker.png";
import Macallan_sherry_oak from "../assets/Macallan_sherry_oak_18.png";
import Jameson from "../assets/Jameson.png";
import Glenfiddich_21 from "../assets/Glenfiddich_21_reserva.png";
import Lagavulin_16 from "../assets/Lagavulin_16.png";
import Redbreast_12 from "../assets/Redbreast_12.png";
import Jack_daniels from "../assets/Jack_daniels.png";
import Yamazaki_12 from "../assets/Yamazaki_12.png";

import Don_julio from "../assets/Don_julio.png";
import Patron_silver from "../assets/Patron_silver.png";
import Tequila_anejo from "../assets/Tequila_anejo.png";
import Jose_silver from "../assets/Jose_silver.png";
import Patron_anejo from "../assets/Patron_anejo.png";
import Olmeca_reposado from "../assets/Olmeca_reposado.png";

import Baileys from "../assets/Baileys.png";
import Martini_rosso from "../assets/Martini_rosso.png";
import Campari from "../assets/Campari.png";
import Hennessy_vs_cognac from "../assets/Hennessy_vs_cognac.png";

import Torley_brut from "../assets/Torley_brut.png";
import Krug_grande from "../assets/Krug_grande.png";
import Tokai_aszu_6 from "../assets/Tokaji_aszu_6.png";
import Bolyki_egri_bikavér from "../assets/Bolyki_egri_bikaver.png";
import Gere_kopar from "../assets/Gere_kopar1.png";
import Bolyki_sauvignon_blanc from "../assets/Bolyki_sauvignon_blanc.png";
import Sauska_rose from "../assets/Sauska_rose.png";
import Château_lafite from "../assets/Château_lafite.png";
import Moet_imperial from "../assets/Moet_imperial.png";
import Château_margaux_2018 from "../assets/Château_margaux_2018.png";
import Laposa_friss from "../assets/Laposa_friss.png";
import Disznoko_furmint from "../assets/Disznoko_furmint.png";
import Szepsy_furmint from "../assets/Szepsy_furmint.png";
import Bock_cabernet_franc from "../assets/Bock_cabernet_franc.png";
import Tiffan_elysium from "../assets/Tiffan_elysium.png";

import Guiness from "../assets/Guiness.png";
import Pilsner_urquell from "../assets/Pilsner_urquell.png";
import Blanc from "../assets/Blanc.png";
import Heineken from "../assets/Heineken.png";
import Paulaner_oktoberfest from "../assets/Paulaner_oktoberfest.png";
import Dreher_gold from "../assets/Dreher_gold.png";
import Dreher_hk from "../assets/Dreher_hk.png";
import Peroni from "../assets/Peroni.png";
import Floris from "../assets/Floris.png";
import Hofbrau_munchen_hefe from "../assets/Hofbrau_munchener_hefe.png";
import Birodalmi_bagoly from "../assets/Birodalmi_bagoly.png";
import Liquid_cocaine from "../assets/Liquid_cocaine.jpg";
import Flying_rabbit from "../assets/Flying_rabbit.png";
import Gentle_bastard from "../assets/Gentle_bastard.png";
import Flower_power from "../assets/Flower_power.png";

import hordo from "../assets/hordo.png";

let ital_product = [
  {
    id: 1,
    name: "Bolyki Sauvignon Blanc 2023",
    category: "alkoholos_italok",
    subcategory: "Bor",
    subsubcategory: "Fehérbor",
    brand: "Bolyki",
    discount: "10%",
    volume: "750 ml",
    alcoholPercentage: "12%",
    description:
      "A 12% alcohol-contented Sauvignon Blanc garnished with rosemary, thyme, and herbs.",
    image: Bolyki_sauvignon_blanc,
    rating: 4.5,
    price: 2100,
  },
  {
    id: 2,
    name: "Heineken Premium Lager",
    category: "alkoholos_italok",
    subcategory: "Sör",
    subsubcategory: "Világos sör",
    brand: "Heineken",
    discount: "15%",
    volume: "500 ml",
    alcoholPercentage: "5%",
    description:
      "Egy klasszikus világos sör, 5% alkoholtartalommal, frissítő ízvilággal.",
    image: Heineken,
    rating: 4.7,
    price: 300.0,
  },
  {
    id: 3,
    name: "Jack Daniel's Tennessee Whiskey",
    category: "alkoholos_italok",
    subcategory: "Whiskey",
    subsubcategory: "Amerikai whiskey",
    brand: "Jack Daniel's",
    discount: "20%",
    volume: "700 ml",
    alcoholPercentage: "40%",
    description:
      "A klasszikus Tennessee whiskey, 40%-os alkoholtartalommal, édeskés és tölgyfás ízjegyekkel.",
    image: Jack_daniels,
    rating: 4.8,
    price: 11000.0,
  },
  {
    id: 4,
    name: "Baileys Irish Cream",
    category: "alkoholos_italok",
    subcategory: "Likőr",
    subsubcategory: "Tejszínes likőr",
    brand: "Baileys",
    discount: "5%",
    volume: "700 ml",
    alcoholPercentage: "17%",
    description:
      "Egy lágy, tejszínes likőr, 17%-os alkoholtartalommal, tökéletes desszertek mellé vagy önmagában.",
    image: Baileys,
    rating: 4.6,
    price: 5500.0,
  },
  {
    id: 5,
    name: "Martini Rosso",
    category: "alkoholos_italok",
    subcategory: "Vermut",
    subsubcategory: "Piros vermut",
    brand: "Martini",
    discount: "10%",
    volume: "1000 ml",
    alcoholPercentage: "15%",
    description:
      "Az ikonikus Martini Rosso, 15%-os alkoholtartalommal, fűszeres és édeskés ízjegyekkel.",
    image: Martini_rosso,
    rating: 4.3,
    price: 4000.0,
  },
  {
    id: 6,
    name: "Moët & Chandon Brut Impérial",
    category: "alkoholos_italok",
    subcategory: "Pezsgő",
    subsubcategory: "Francia pezsgő",
    brand: "Moët & Chandon",
    discount: "12%",
    volume: "750 ml",
    alcoholPercentage: "12%",
    description:
      "Egy prémium francia pezsgő, 12%-os alkoholtartalommal, citrusos és virágos jegyekkel.",
    image: Moet_imperial,
    rating: 4.9,
    price: 18000.0,
  },
  {
    id: 7,
    name: "Grey Goose Vodka",
    category: "alkoholos_italok",
    subcategory: "Vodka",
    subsubcategory: "Prémium vodka",
    brand: "Grey Goose",
    discount: "15%",
    volume: "700 ml",
    alcoholPercentage: "40%",
    description:
      "Egy prémium francia vodka, 40%-os alkoholtartalommal, lágy, tiszta ízvilággal.",
    image: Grey_goose,
    rating: 4.8,
    price: 12000.0,
  },
  {
    id: 8,
    name: "Törley Excellence Brut",
    category: "alkoholos_italok",
    subcategory: "Pezsgő",
    subsubcategory: "Magyar pezsgő",
    brand: "Törley",
    discount: "10%",
    volume: "750 ml",
    alcoholPercentage: "12.5%",
    description:
      "Törley Excellence Brut, 12.5%-os alkoholtartalommal, frissítő és száraz pezsgő.",
    image: Torley_brut,
    rating: 4.4,
    price: 3500.0,
  },
  {
    id: 9,
    name: "Johnnie Walker Black Label",
    category: "alkoholos_italok",
    subcategory: "Whiskey",
    subsubcategory: "Skót whiskey",
    brand: "Johnnie Walker",
    discount: "18%",
    volume: "700 ml",
    alcoholPercentage: "40%",
    description:
      "A híres Black Label, 40%-os alkoholtartalommal, komplex és füstös ízvilággal.",
    image: Johnnie_walker,
    rating: 4.7,
    price: 9500.0,
  },
  {
    id: 10,
    name: "Château Margaux 2018",
    category: "alkoholos_italok",
    subcategory: "Bor",
    subsubcategory: "Vörösbor",
    brand: "Château Margaux",
    discount: "5%",
    volume: "750 ml",
    alcoholPercentage: "13.5%",
    description:
      "Egy prémium vörösbor Bordeaux-ból, 13.5%-os alkoholtartalommal, mély, gazdag ízekkel.",
    image: Château_margaux_2018,
    rating: 4.9,
    price: 220000.0,
  },
  {
    id: 11,
    name: "Campari",
    category: "alkoholos_italok",
    subcategory: "Likőr",
    subsubcategory: "Keserű likőr",
    brand: "Campari",
    discount: "8%",
    volume: "1000 ml",
    alcoholPercentage: "25%",
    description:
      "Egy klasszikus olasz keserű likőr, 25%-os alkoholtartalommal, citrusos és fűszeres jegyekkel.",
    image: Campari,
    rating: 4.5,
    price: 7000.0,
  },
  {
    id: 12,
    name: "Absolut Vodka",
    category: "alkoholos_italok",
    subcategory: "Vodka",
    subsubcategory: "Svéd vodka",
    brand: "Absolut",
    discount: "12%",
    volume: "700 ml",
    alcoholPercentage: "40%",
    description:
      "A híres svéd vodka, 40%-os alkoholtartalommal, tiszta és semleges ízvilággal.",
    image: Absolut,
    rating: 4.6,
    price: 5000.0,
  },
  {
    id: 13,
    name: "Patrón Silver Tequila",
    category: "alkoholos_italok",
    subcategory: "Tequila",
    subsubcategory: "Prémium tequila",
    brand: "Patrón",
    discount: "20%",
    volume: "700 ml",
    alcoholPercentage: "40%",
    description:
      "Egy prémium mexikói tequila, 40%-os alkoholtartalommal, friss és citrusos ízvilággal.",
    image: Patron_silver,
    rating: 4.8,
    price: 16000.0,
  },
  {
    id: 14,
    name: "Bombay Sapphire Gin",
    category: "alkoholos_italok",
    subcategory: "Gin",
    subsubcategory: "Prémium gin",
    brand: "Bombay Sapphire",
    discount: "10%",
    volume: "700 ml",
    alcoholPercentage: "40%",
    description:
      "Egy klasszikus prémium gin, 40%-os alkoholtartalommal, borókás és citrusos ízekkel.",
    image: Bombay_sapphire,
    rating: 4.7,
    price: 7000.0,
  },
  {
    id: 15,
    name: "Gordon's Pink Gin",
    category: "alkoholos_italok",
    subcategory: "Gin",
    subsubcategory: "Ízesített gin",
    brand: "Gordon's",
    discount: "15%",
    volume: "700 ml",
    alcoholPercentage: "37.5%",
    description:
      "Egy gyümölcsös ízesített gin, 37.5%-os alkoholtartalommal, eper és málna jegyekkel.",
    image: Gordons,
    rating: 4.4,
    price: 6500.0,
  },
  {
    id: 16,
    name: "Captain Morgan Spiced Gold",
    category: "alkoholos_italok",
    subcategory: "Rum",
    subsubcategory: "Fűszeres rum",
    brand: "Captain Morgan",
    discount: "10%",
    volume: "700 ml",
    alcoholPercentage: "35%",
    description:
      "Egy fűszeres karibi rum, 35%-os alkoholtartalommal, vaníliás és fahéjas ízekkel.",
    image: Captain_morgan,
    rating: 4.6,
    price: 6500.0,
  },
  {
    id: 17,
    name: "Hennessy VS Cognac",
    category: "alkoholos_italok",
    subcategory: "Cognac",
    subsubcategory: "Francia cognac",
    brand: "Hennessy",
    discount: "12%",
    volume: "700 ml",
    alcoholPercentage: "40%",
    description:
      "Egy prémium francia cognac, 40%-os alkoholtartalommal, gazdag és fás ízjegyekkel.",
    image: Hennessy_vs_cognac,
    rating: 4.8,
    price: 15000.0,
  },
  {
    id: 18,
    name: "Jameson Irish Whiskey",
    category: "alkoholos_italok",
    subcategory: "Whiskey",
    subsubcategory: "Ír whiskey",
    brand: "Jameson",
    discount: "10%",
    volume: "700 ml",
    alcoholPercentage: "40%",
    description:
      "Egy klasszikus ír whiskey, 40%-os alkoholtartalommal, sima és édes ízvilággal.",
    image: Jameson,
    rating: 4.7,
    price: 8000.0,
  },
  {
    id: 19,
    name: "Malfy Gin Rosa",
    category: "alkoholos_italok",
    subcategory: "Gin",
    subsubcategory: "Ízesített gin",
    brand: "Malfy",
    discount: "15%",
    volume: "700 ml",
    alcoholPercentage: "41%",
    description:
      "Egy olasz ízesített gin, 41%-os alkoholtartalommal, grapefruit és rebarbara ízekkel.",
    image: Malfy_rosa,
    rating: 4.6,
    price: 8500.0,
  },
  {
    id: 20,
    name: "Don Julio Añejo Tequila",
    category: "alkoholos_italok",
    subcategory: "Tequila",
    subsubcategory: "Añejo tequila",
    brand: "Don Julio",
    discount: "18%",
    volume: "700 ml",
    alcoholPercentage: "38%",
    description:
      "Egy prémium añejo tequila, 38%-os alkoholtartalommal, mély karamellás és fás ízjegyekkel.",
    image: Don_julio,
    rating: 4.9,
    price: 18000.0,
  },
  {
    id: 21,
    name: "Krug Grande Cuvée",
    category: "alkoholos_italok",
    subcategory: "Pezsgő",
    subsubcategory: "Francia pezsgő",
    brand: "Krug",
    discount: "5%",
    volume: "750 ml",
    alcoholPercentage: "12%",
    description:
      "Egy prémium francia pezsgő, 12%-os alkoholtartalommal, komplex és gazdag ízvilággal.",
    image: Krug_grande,
    rating: 4.9,
    price: 50000.0,
  },
  {
    id: 22,
    name: "Tokaji Aszú 6 Puttonyos 2017",
    category: "alkoholos_italok",
    subcategory: "Bor",
    subsubcategory: "Desszertbor",
    brand: "Tokaji",
    discount: "10%",
    volume: "500 ml",
    alcoholPercentage: "11%",
    description:
      "A híres 6 puttonyos Tokaji Aszú, 11%-os alkoholtartalommal, mély, édes és gazdag ízvilággal.",
    image: Tokai_aszu_6,
    rating: 4.9,
    price: 18000.0,
  },
  {
    id: 23,
    name: "Bolyki Egri Bikavér 2019",
    category: "alkoholos_italok",
    subcategory: "Bor",
    subsubcategory: "Vörösbor",
    brand: "Bolyki",
    discount: "12%",
    volume: "750 ml",
    alcoholPercentage: "13%",
    description:
      "Egy klasszikus magyar vörösbor, 13%-os alkoholtartalommal, erős, fűszeres és gyümölcsös jegyekkel.",
    image: Bolyki_egri_bikavér,
    rating: 4.7,
    price: 3500.0,
  },
  {
    id: 24,
    name: "Laposa Friss 2023",
    category: "alkoholos_italok",
    subcategory: "Bor",
    subsubcategory: "Fehérbor",
    brand: "Laposa",
    discount: "8%",
    volume: "750 ml",
    alcoholPercentage: "11.5%",
    description:
      "Egy friss és savas fehérbor, 12%-os alkoholtartalommal, citrusos és ásványos ízjegyekkel.",
    image: Laposa_friss,
    rating: 4.5,
    price: 2700.0,
  },
  {
    id: 25,
    name: "Disznókő Furmint 2021",
    category: "alkoholos_italok",
    subcategory: "Bor",
    subsubcategory: "Fehérbor",
    brand: "Disznókő",
    discount: "15%",
    volume: "750 ml",
    alcoholPercentage: "12.5%",
    description:
      "Egy tokaji száraz furmint, 12.5%-os alkoholtartalommal, friss, gyümölcsös és ásványos ízvilággal.",
    image: Disznoko_furmint,
    rating: 4.6,
    price: 3200.0,
  },
  {
    id: 26,
    name: "Château Lafite Rothschild 2018",
    category: "alkoholos_italok",
    subcategory: "Bor",
    subsubcategory: "Vörösbor",
    brand: "Château Lafite Rothschild",
    discount: "5%",
    volume: "750 ml",
    alcoholPercentage: "13.5%",
    description:
      "Egy világhírű bordeaux-i vörösbor, 13.5%-os alkoholtartalommal, komplex, gazdag ízjegyekkel.",
    image: Château_lafite,
    rating: 4.9,
    price: 250000.0,
  },
  {
    id: 27,
    name: "Gere Attila Kopar Cuvée 2017",
    category: "alkoholos_italok",
    subcategory: "Bor",
    subsubcategory: "Vörösbor",
    brand: "Gere Attila",
    discount: "10%",
    volume: "750 ml",
    alcoholPercentage: "14.5%",
    description:
      "Egy ikonikus villányi cuvée, 14.5%-os alkoholtartalommal, erőteljes, fás és fűszeres ízvilággal.",
    image: Gere_kopar,
    rating: 4.8,
    price: 13000.0,
  },
  {
    id: 28,
    name: "Szepsy Tokaji Furmint 2020",
    category: "alkoholos_italok",
    subcategory: "Bor",
    subsubcategory: "Fehérbor",
    brand: "Szepsy",
    discount: "12%",
    volume: "750 ml",
    alcoholPercentage: "13%",
    description:
      "Egy kiváló tokaji furmint, 13%-os alkoholtartalommal, ásványos és gyümölcsös jegyekkel.",
    image: Szepsy_furmint,
    rating: 4.9,
    price: 9000.0,
  },
  {
    id: 29,
    name: "Bock Cabernet Franc 2018",
    category: "alkoholos_italok",
    subcategory: "Bor",
    subsubcategory: "Vörösbor",
    brand: "Bock",
    discount: "10%",
    volume: "750 ml",
    alcoholPercentage: "14%",
    description:
      "Egy gazdag és mély cabernet franc Villányból, 14%-os alkoholtartalommal, fűszeres és gyümölcsös ízekkel.",
    image: Bock_cabernet_franc,
    rating: 4.7,
    price: 6000.0,
  },
  {
    id: 30,
    name: "Sauska Rosé 2022",
    category: "alkoholos_italok",
    subcategory: "Bor",
    subsubcategory: "Rozé",
    brand: "Sauska",
    discount: "8%",
    volume: "750 ml",
    alcoholPercentage: "12.5%",
    description:
      "Egy könnyed és friss rozé, 12.5%-os alkoholtartalommal, piros bogyós gyümölcsök ízével.",
    image: Sauska_rose,
    rating: 4.5,
    price: 3500.0,
  },
  {
    id: 31,
    name: "Tiffán Elysium Cuvée 2016",
    category: "alkoholos_italok",
    subcategory: "Bor",
    subsubcategory: "Vörösbor",
    brand: "Tiffán",
    discount: "15%",
    volume: "750 ml",
    alcoholPercentage: "14.5%",
    description:
      "Egy prémium cuvée Villányból, 14.5%-os alkoholtartalommal, gazdag és bársonyos ízekkel.",
    image: Tiffan_elysium,
    rating: 4.8,
    price: 11000.0,
  },
  {
    id: 32,
    name: "Yamazaki 12 Year Old",
    category: "alkoholos_italok",
    subcategory: "Whiskey",
    subsubcategory: "Japán whiskey",
    brand: "Yamazaki",
    discount: "8%",
    volume: "700 ml",
    alcoholPercentage: "43%",
    description:
      "Egy prémium japán single malt whiskey, 43%-os alkoholtartalommal, gazdag gyümölcsös és tölgyes ízvilággal.",
    image: Yamazaki_12,
    rating: 4.9,
    price: 45000.0,
  },
  {
    id: 33,
    name: "Macallan Sherry Oak 18 Year Old",
    category: "alkoholos_italok",
    subcategory: "Whiskey",
    subsubcategory: "Skót whiskey",
    brand: "Macallan",
    discount: "5%",
    volume: "700 ml",
    alcoholPercentage: "43%",
    description:
      "Egy skót single malt whiskey, 43%-os alkoholtartalommal, sherrys jegyekkel, gazdag és komplex ízvilággal.",
    image: Macallan_sherry_oak,
    rating: 4.9,
    price: 200000.0,
  },
  {
    id: 34,
    name: "Glenfiddich 21 Year Old Reserva Rum Cask",
    category: "alkoholos_italok",
    subcategory: "Whiskey",
    subsubcategory: "Skót whiskey",
    brand: "Glenfiddich",
    discount: "7%",
    volume: "700 ml",
    alcoholPercentage: "40%",
    description:
      "Egy 21 éves single malt whiskey, rum hordós érleléssel, 40%-os alkoholtartalommal, édes, gyümölcsös jegyekkel.",
    image: Glenfiddich_21,
    rating: 4.8,
    price: 91000.0,
  },
  {
    id: 35,
    name: "Lagavulin 16 Year Old",
    category: "alkoholos_italok",
    subcategory: "Whiskey",
    subsubcategory: "Skót whiskey",
    brand: "Lagavulin",
    discount: "10%",
    volume: "700 ml",
    alcoholPercentage: "43%",
    description:
      "Egy erőteljes, füstös skót whiskey, 43%-os alkoholtartalommal, gazdag és intenzív ízvilággal.",
    image: Lagavulin_16,
    rating: 4.7,
    price: 45000.0,
  },
  {
    id: 36,
    name: "Redbreast 12 Year Old",
    category: "alkoholos_italok",
    subcategory: "Whiskey",
    subsubcategory: "Ír whiskey",
    brand: "Redbreast",
    discount: "12%",
    volume: "700 ml",
    alcoholPercentage: "40%",
    description:
      "Egy klasszikus ír single pot still whiskey, 40%-os alkoholtartalommal, gyümölcsös és fűszeres jegyekkel.",
    image: Redbreast_12,
    rating: 4.8,
    price: 22000.0,
  },
  {
    id: 37,
    name: "Monkey 47 Schwarzwald Dry Gin",
    category: "alkoholos_italok",
    subcategory: "Gin",
    subsubcategory: "Prémium gin",
    brand: "Monkey 47",
    discount: "8%",
    volume: "500 ml",
    alcoholPercentage: "47%",
    description:
      "Egy német prémium gin 47%-os alkoholtartalommal, 47 különböző növénnyel és fűszerrel.",
    image: Monkey_47,
    rating: 4.9,
    price: 15000.0,
  },
  {
    id: 38,
    name: "Hendrick's Gin",
    category: "alkoholos_italok",
    subcategory: "Gin",
    subsubcategory: "Prémium gin",
    brand: "Hendrick's",
    discount: "10%",
    volume: "700 ml",
    alcoholPercentage: "41.4%",
    description:
      "Egy különleges skót gin, 41.4%-os alkoholtartalommal, rózsa és uborka egyedi jegyeivel.",
    image: Hendricks,
    rating: 4.8,
    price: 12000.0,
  },
  {
    id: 39,
    name: "The Botanist Islay Dry Gin",
    category: "alkoholos_italok",
    subcategory: "Gin",
    subsubcategory: "Prémium gin",
    brand: "The Botanist",
    discount: "8%",
    volume: "700 ml",
    alcoholPercentage: "46%",
    description:
      "Egy prémium gin Islay szigetéről, 46%-os alkoholtartalommal, 22 helyi gyógynövénnyel.",
    image: Botanist,
    rating: 4.7,
    price: 13500.0,
  },
  {
    id: 40,
    name: "Sipsmith London Dry Gin",
    category: "alkoholos_italok",
    subcategory: "Gin",
    subsubcategory: "Prémium gin",
    brand: "Sipsmith",
    discount: "12%",
    volume: "700 ml",
    alcoholPercentage: "41.6%",
    description:
      "Egy klasszikus londoni száraz gin, 41.6%-os alkoholtartalommal, borókás és citrusos ízjegyekkel.",
    image: Sipssmith,
    rating: 4.6,
    price: 10000.0,
  },
  {
    id: 41,
    name: "Gin Mare Mediterranean",
    category: "alkoholos_italok",
    subcategory: "Gin",
    subsubcategory: "Prémium gin",
    brand: "Gin Mare",
    discount: "10%",
    volume: "700 ml",
    alcoholPercentage: "42.7%",
    description:
      "Egy mediterrán ihletésű gin, 42.7%-os alkoholtartalommal, rozmaring, olíva és bazsalikom jegyekkel.",
    image: Gin_mare,
    rating: 4.7,
    price: 13500.0,
  },
  {
    id: 42,
    name: "Diplomático Reserva Exclusiva",
    category: "alkoholos_italok",
    subcategory: "Rum",
    subsubcategory: "Prémium rum",
    brand: "Diplomático",
    discount: "10%",
    volume: "700 ml",
    alcoholPercentage: "40%",
    description:
      "Egy venezuelai prémium rum, 40%-os alkoholtartalommal, édes, karamelles és fás jegyekkel.",
    image: Diplomatico,
    rating: 4.9,
    price: 15000.0,
  },
  {
    id: 43,
    name: "Zacapa Centenario 23",
    category: "alkoholos_italok",
    subcategory: "Rum",
    subsubcategory: "Prémium rum",
    brand: "Zacapa",
    discount: "5%",
    volume: "700 ml",
    alcoholPercentage: "40%",
    description:
      "Egy guatemalai prémium rum, 23 éves érleléssel, 40%-os alkoholtartalommal, mély és gazdag ízekkel.",
    image: Zacapa_23,
    rating: 4.8,
    price: 18000.0,
  },
  {
    id: 44,
    name: "Mount Gay XO Triple Cask Blend",
    category: "alkoholos_italok",
    subcategory: "Rum",
    subsubcategory: "Prémium rum",
    brand: "Mount Gay",
    discount: "8%",
    volume: "700 ml",
    alcoholPercentage: "43%",
    description:
      "Egy barbadosi prémium rum, 43%-os alkoholtartalommal, komplex és fűszeres ízjegyekkel.",
    image: Mount_gay_xo,
    rating: 4.7,
    price: 20000.0,
  },
  {
    id: 45,
    name: "El Dorado 15 Year Old",
    category: "alkoholos_italok",
    subcategory: "Rum",
    subsubcategory: "Prémium rum",
    brand: "El Dorado",
    discount: "7%",
    volume: "700 ml",
    alcoholPercentage: "43%",
    description:
      "Egy guyanai prémium rum, 15 éves érleléssel, 43%-os alkoholtartalommal, gazdag, fás és mézes ízjegyekkel.",
    image: El_dorado_15,
    rating: 4.8,
    price: 17000.0,
  },
  {
    id: 46,
    name: "Plantation XO 20th Anniversary",
    category: "alkoholos_italok",
    subcategory: "Rum",
    subsubcategory: "Prémium rum",
    brand: "Plantation",
    discount: "10%",
    volume: "700 ml",
    alcoholPercentage: "40%",
    description:
      "Egy barbadosi rum, 40%-os alkoholtartalommal, gazdag és komplex ízvilággal, trópusi gyümölcsök és vanília jegyekkel.",
    image: Plantation_xo,
    rating: 4.9,
    price: 16000.0,
  },
  {
    id: 47,
    name: "Guinness Draught KEG 30L",
    category: "alkoholos_italok",
    subcategory: "Sör",
    subsubcategory: "Stout",
    brand: "Guinness",
    discount: "10%",
    volume: "30l",
    alcoholPercentage: "4.2%",
    description:
      "Az ikonikus ír stout hordós változata, 4.2%-os alkoholtartalommal, gazdag, pörkölt maláta ízjegyekkel.",
    image: Guiness,
    rating: 4.8,
    price: 40000,
  },
  {
    id: 48,
    name: "Pilsner Urquell KEG 30L",
    category: "alkoholos_italok",
    subcategory: "Sör",
    subsubcategory: "Lager",
    brand: "Pilsner Urquell",
    discount: "8%",
    volume: "30l",
    alcoholPercentage: "4.4%",
    description:
      "A cseh pilseni stílusú sör hordós változata, 4.4%-os alkoholtartalommal, könnyed, friss és kesernyés ízzel.",
    image: Pilsner_urquell,
    rating: 4.7,
    price: 38000,
  },
  {
    id: 49,
    name: "Kronenbourg Blanc búzasör KEG 30L",
    category: "alkoholos_italok",
    subcategory: "Sör",
    subsubcategory: "Búzasör",
    brand: "Kronenbourg",
    discount: "7%",
    volume: "30l",
    alcoholPercentage: "5%",
    description:
      "Egy klasszikus német búzasör, 5%-os alkoholtartalommal, banános és szegfűszeges jegyekkel.",
    image: Blanc,
    rating: 4.9,
    price: 42000,
  },
  {
    id: 50,
    name: "Heineken KEG 30L",
    category: "alkoholos_italok",
    subcategory: "Sör",
    subsubcategory: "Lager",
    brand: "Heineken",
    discount: "5%",
    volume: "30l",
    alcoholPercentage: "5%",
    description:
      "A népszerű világos lager hordós változata, 5%-os alkoholtartalommal, könnyed és frissítő ízvilággal.",
    image: hordo,
    rating: 4.5,
    price: 35000,
  },
  {
    id: 51,
    name: "Paulaner Oktoberfestbier KEG 30L",
    category: "alkoholos_italok",
    subcategory: "Sör",
    subsubcategory: "Märzen",
    brand: "Paulaner",
    discount: "10%",
    volume: "30l",
    alcoholPercentage: "6%",
    description:
      "A híres német Oktoberfest sör, 6%-os alkoholtartalommal, gazdag malátás ízvilággal.",
    image: Paulaner_oktoberfest,
    rating: 4.7,
    price: 45000,
  },
  {
    id: 52,
    name: "Dreher Gold KEG 30L",
    category: "alkoholos_italok",
    subcategory: "Sör",
    subsubcategory: "Lager",
    brand: "Dreher",
    discount: "7%",
    volume: "30l",
    alcoholPercentage: "5.2%",
    description:
      "A Dreher Gold hordós változata, 5.2%-os alkoholtartalommal, gazdag malátás és frissítő ízvilággal.",
    image: Dreher_gold,
    rating: 4.6,
    price: 37000,
  },
  {
    id: 53,
    name: "Dreher Hidegkomlós KEG 30L",
    category: "alkoholos_italok",
    subcategory: "Sör",
    subsubcategory: "Lager",
    brand: "Dreher",
    discount: "6%",
    volume: "30l",
    alcoholPercentage: "4.8%",
    description:
      "A Dreher Hidegkomlós hordós változata, 4.8%-os alkoholtartalommal, különleges hidegkomlós technológiával készült, friss és komlós ízvilággal.",
    image: Dreher_hk,
    rating: 4.7,
    price: 36000,
  },
  {
    id: 54,
    name: "Peroni Nastro Azzurro KEG 30L",
    category: "alkoholos_italok",
    subcategory: "Sör",
    subsubcategory: "Lager",
    brand: "Peroni",
    discount: "5%",
    volume: "30l",
    alcoholPercentage: "5.1%",
    description:
      "Az olasz Peroni Nastro Azzurro sör hordós változata, 5.1%-os alkoholtartalommal, könnyed, friss és citrusos ízjegyekkel.",
    image: Peroni,
    rating: 4.8,
    price: 39000,
  },
  {
    id: 55,
    name: "Floris Kriek KEG 30L",
    category: "alkoholos_italok",
    subcategory: "Sör",
    subsubcategory: "Gyümölcsös sör",
    brand: "Floris",
    discount: "10%",
    volume: "30l",
    alcoholPercentage: "3.6%",
    description:
      "Egy belga meggyes sör, 3.6%-os alkoholtartalommal, frissítő gyümölcsös és enyhén savanykás ízvilággal.",
    image: Floris,
    rating: 4.9,
    price: 43000,
  },
  {
    id: 56,
    name: "Hofbräu München Hefe Weizen KEG 20L",
    category: "alkoholos_italok",
    subcategory: "Sör",
    subsubcategory: "Búzasör",
    brand: "Hofbräu",
    discount: "8%",
    volume: "20l",
    alcoholPercentage: "5.1%",
    description:
      "A népszerű német búzasör hordós változata, 5.1%-os alkoholtartalommal, klasszikus banános és szegfűszeges jegyekkel.",
    image: Hofbrau_munchen_hefe,
    rating: 4.7,
    price: 40000,
  },
  {
    id: 57,
    name: "Mad Scientist Liquid Cocaine KEG 30L",
    category: "alkoholos_italok",
    subcategory: "Sör",
    subsubcategory: "IPA",
    brand: "Mad Scientist",
    discount: "7%",
    volume: "30l",
    alcoholPercentage: "8%",
    description:
      "Egy erőteljes, magyar kézműves dupla IPA, 8%-os alkoholtartalommal, intenzív komlós és citrusos ízjegyekkel.",
    image: Liquid_cocaine,
    rating: 4.8,
    price: 48000,
  },
  {
    id: 58,
    name: "MONYO Flying Rabbit KEG 30L",
    category: "alkoholos_italok",
    subcategory: "Sör",
    subsubcategory: "IPA",
    brand: "MONYO",
    discount: "6%",
    volume: "30l",
    alcoholPercentage: "6.5%",
    description:
      "A MONYO Brewing egyik legismertebb IPA-ja, 6.5%-os alkoholtartalommal, frissítő trópusi gyümölcsös és fenyős ízvilággal.",
    image: Flying_rabbit,
    rating: 4.7,
    price: 45000,
  },
  {
    id: 59,
    name: "Horizont Gentle Bastard KEG 30L",
    category: "alkoholos_italok",
    subcategory: "Sör",
    subsubcategory: "APA",
    brand: "Horizont",
    discount: "5%",
    volume: "30l",
    alcoholPercentage: "5.6%",
    description:
      "Egy könnyed, friss magyar kézműves American Pale Ale, 5.6%-os alkoholtartalommal, citrusos és fenyős jegyekkel.",
    image: Gentle_bastard,
    rating: 4.6,
    price: 62000,
  },
  {
    id: 60,
    name: "First Flower Power KEG 20L",
    category: "alkoholos_italok",
    subcategory: "Sör",
    subsubcategory: "Neipa",
    brand: "First Craft Beer",
    discount: "8%",
    volume: "20l",
    alcoholPercentage: "6.3%",
    description:
      "Egy magyar kézműves Kölsch stílusú sör, 4.8%-os alkoholtartalommal, könnyed, malátás és gyümölcsös ízvilággal.",
    image: Flower_power,
    rating: 4.7,
    price: 40000,
  },
  {
    id: 61,
    name: "Balkezes Birodalmi Bagoly KEG 20L",
    category: "alkoholos_italok",
    subcategory: "Sör",
    subsubcategory: "Porter",
    brand: "Balkezes",
    discount: "9%",
    volume: "20l",
    alcoholPercentage: "12%",
    description:
      "Egy magyar kézműves mogyorós porter, 12%-os alkoholtartalommal, pörkölt malátás és mogyorós ízjegyekkel.",
    image: Birodalmi_bagoly,
    rating: 4.8,
    price: 55000,
  },
  {
    id: 62,
    name: "Bacardi Carta Blanca",
    category: "alkoholos_italok",
    subcategory: "Rum",
    subsubcategory: "Fehér rum",
    brand: "Bacardi",
    discount: "5%",
    volume: "1l",
    alcoholPercentage: "37.5%",
    description:
      "A Bacardi Carta Blanca egy klasszikus fehér rum, 37.5%-os alkoholtartalommal, tiszta és friss ízjegyekkel, ideális koktélokhoz.",
    image: Bacardi_carta_blanca,
    rating: 4.6,
    price: 8000,
  },
  {
    id: 63,
    name: "Bacardi Spiced",
    category: "alkoholos_italok",
    subcategory: "Rum",
    subsubcategory: "Fűszeres rum",
    brand: "Bacardi",
    discount: "6%",
    volume: "1l",
    alcoholPercentage: "35%",
    description:
      "A Bacardi Spiced egy fűszeres rum, 35%-os alkoholtartalommal, gazdag vaníliás és fahéjas ízjegyekkel, remekül alkalmas koktélokhoz vagy önállóan fogyasztva.",
    image: Bacardi_spiced,
    rating: 4.7,
    price: 8500,
  },
  {
    id: 64,
    name: "Bacardi Carta Negra",
    category: "alkoholos_italok",
    subcategory: "Rum",
    subsubcategory: "Barna rum",
    brand: "Bacardi",
    discount: "6%",
    volume: "700ml",
    alcoholPercentage: "35%",
    description:
      "A Bacardi Spiced egy fűszeres rum, 35%-os alkoholtartalommal, gazdag vaníliás és fahéjas ízjegyekkel, remekül alkalmas koktélokhoz vagy önállóan fogyasztva.",
    image: Bacardi_carta_negra,
    rating: 4.7,
    price: 9000,
  },
  {
    id: 65,
    name: "Jose Cuervo Especial Silver",
    category: "alkoholos_italok",
    subcategory: "Tequila",
    subsubcategory: "Fehér tequila",
    brand: "Jose Cuervo",
    discount: "5%",
    volume: "700ml",
    alcoholPercentage: "38%",
    description:
      "A Jose Cuervo Especial Silver egy tiszta, friss fehér tequila, 38%-os alkoholtartalommal, enyhén citrusos és borsos ízjegyekkel, ideális koktélokhoz.",
    image: Jose_silver,
    rating: 4.6,
    price: 8500,
  },
  {
    id: 66,
    name: "Patrón Añejo",
    category: "alkoholos_italok",
    subcategory: "Tequila",
    subsubcategory: "Añejo tequila",
    brand: "Patrón",
    discount: "7%",
    volume: "700ml",
    alcoholPercentage: "40%",
    description:
      "A Patrón Añejo egy prémium érlelt tequila, 40%-os alkoholtartalommal, gazdag tölgyfás, vaníliás és karamellás jegyekkel, amely önmagában vagy koktélokban is kiváló.",
    image: Patron_anejo,
    rating: 4.9,
    price: 18000,
  },
  {
    id: 67,
    name: "Olmeca Altos Reposado",
    category: "alkoholos_italok",
    subcategory: "Tequila",
    subsubcategory: "Reposado tequila",
    brand: "Olmeca",
    discount: "6%",
    volume: "700ml",
    alcoholPercentage: "38%",
    description:
      "Az Olmeca Altos Reposado egy kiváló minőségű, érlelt tequila, 38%-os alkoholtartalommal, kiegyensúlyozott tölgyes és agávés ízekkel.",
    image: Olmeca_reposado,
    rating: 4.7,
    price: 12000,
  },
  {
    id: 68,
    name: "1800 Añejo",
    category: "alkoholos_italok",
    subcategory: "Tequila",
    subsubcategory: "Añejo tequila",
    brand: "1800 Tequila",
    discount: "6%",
    volume: "700ml",
    alcoholPercentage: "40%",
    description:
      "A 1800 Añejo egy érlelt tequila, 40%-os alkoholtartalommal, mély karamellás és fás jegyekkel, elegáns választás önálló fogyasztásra.",
    image: Tequila_anejo,
    rating: 4.9,
    price: 19000,
  },
  {
    id: 70,
    name: "Beluga Noble Vodka",
    category: "alkoholos_italok",
    subcategory: "Vodka",
    subsubcategory: "Tiszta vodka",
    brand: "Beluga",
    discount: "7%",
    volume: "700ml",
    alcoholPercentage: "40%",
    description:
      "A Beluga Noble Vodka egy prémium orosz vodka, 40%-os alkoholtartalommal, lágy és gazdag ízvilággal, amely önmagában vagy koktélokban is tökéletesen megállja a helyét.",
    image: Beluga,
    rating: 4.9,
    price: 17000,
  },
  {
    id: 71,
    name: "Ciroc Vodka",
    category: "alkoholos_italok",
    subcategory: "Vodka",
    subsubcategory: "Tiszta vodka",
    brand: "Ciroc",
    discount: "6%",
    volume: "700ml",
    alcoholPercentage: "40%",
    description:
      "A Ciroc Vodka egy francia prémium vodka, amely szőlőből készül, 40%-os alkoholtartalommal, sima és gyümölcsös ízjegyekkel.",
    image: Ciroc,
    rating: 4.8,
    price: 16000,
  },
];

export default ital_product;
