stages:
  - sync

sync_to_github:
  stage: sync
  script:
    - git remote add github https://<ketonBever0>:${GITHUB_TOKEN}@github.com/<ketonBever0>/<rf1-italpont>.git
    - git push github --all
    - git push github --tags
  only:
    - main
